### ISSUE TITLE
downloadable font: download failed, cross-site access not allowed

### ISSUE THREAD

**Issue by int-ua** [domoritz/leaflet-locatecontrol#125]
After adding all CDN links font is not loading in Firefox:

> downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:2): bad URI or cross-site access not allowed source: https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/fonts/fontawesome-webfont.woff?v=4.3.0

**Comment by int-ua** [comment]
Reproducible on the example:
https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-locatecontrol/

**Comment by int-ua** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/6651

**Comment by int-ua** [comment]
Also, loading almost 1Mb font just for one tiny icon looks like a really bad choice to me.

**Comment by domoritz** [comment]
I don't see the problem in firefox with the demo from http://domoritz.de/leaflet-locatecontrol/demo/. Can you please try it. For mapbox, try http://domoritz.de/leaflet-locatecontrol/demo_mapbox/. For the example that you showed me, I see that there is a cross origin policy issue on their side. It's not really a problem with my library. 

Concerning the size, I don't see the issue. The web font is 50 KB and not 1 MB. I agree that 1 MB would be bad but it's not the case. I'm closing the issue for now because I cannot reproduce it and it's not an issue that I can fix. Please report the issue at https://github.com/mapbox/mapbox.js-plugins/issues/new

![screen shot 2015-06-04 at 14 41 36](https://cloud.githubusercontent.com/assets/589034/7995100/e3bcee12-0ac7-11e5-8cb0-5d6346c6c313.png)

**Comment by gamecubate** [comment]
This issue is not specific to Firefox. It can be observed in Chrome and is very much alive. :(

To reproduce:
1. launch Chrome
2. in Chrome, open JS console
3. go to https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-locatecontrol/
4. observe that:
a. no icon displayed in leaflet locate control
b. console reports cross-site problem.

Note: the sample code from mapbox is as follows:

```
<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
<title>Leaflet Locate</title>
<meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
<script src='https://api.tiles.mapbox.com/mapbox.js/v2.2.0/mapbox.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox.js/v2.2.0/mapbox.css' rel='stylesheet' />
<style>
  body { margin:0; padding:0; }
  #map { position:absolute; top:0; bottom:0; width:100%; }
</style>
</head>
<body>
<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.mapbox.css' rel='stylesheet' />
<!--[if lt IE 9]>
<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.ie.css' rel='stylesheet' />
<![endif]-->
<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/css/font-awesome.min.css' rel='stylesheet' />

<div id='map'></div>
<script>
L.mapbox.accessToken = 'pk.eyJ1IjoiaW5mb2pkZW0iLCJhIjoiVkJKT2ZjOCJ9.pj-RGZgqDtab-IYB65hjcA';
    var map = L.mapbox.map('map', 'mapbox.streets');
    L.control.locate().addTo(map);
</script>
</body>
</html>
```

**Comment by domoritz** [comment]
Can you report this problem at https://github.com/mapbox/mapbox.js-plugins/issues/new?

**Comment by gamecubate** [comment]
[Reported](https://github.com/mapbox/mapbox.js-plugins/issues/29).
