### ISSUE TITLE
setStyle does not exist for L.Marker

### ISSUE THREAD

**Issue by GarySiu** [domoritz/leaflet-locatecontrol#169]
setStyle only exists for L.CircleMarker so this commit: https://github.com/domoritz/leaflet-locatecontrol/commit/2c06bfdf791e1a33e424018cfabab378d81e7097 actually broke the control for anyone using the alternative marker style. Not sure how you want to approach this.

**Comment by domoritz** [comment]
Interesting. I did not consider this issue because I usually use a circle marker and only intended the marker class to be a subclass or circle markers. 

https://github.com/domoritz/leaflet-locatecontrol/pull/165 is about the same issue, I suppose. 

I think the only solution is to only call `setStyle` if it exists on the class.

**Comment by GarySiu** [comment]
The Marker class would still need styling applied though. We just switched to using the circle marker for now.

**Comment by domoritz** [comment]
> The Marker class would still need styling applied though.

I don't understand. If the marker does not support styling, we have to ignore the style.

**Comment by GarySiu** [comment]
Marker doesn't support #setStyle but it does have a number of options/attributes that affect how it's styled: http://leafletjs.com/examples/custom-icons.html

These still need to be passed on. I'm sure you were going to do that anyway, just wanted to be explicit!
