### ISSUE TITLE
Geolocation error: Network location provider at 'https://www.googleapis.com/' : Returned error code 400.

### ISSUE THREAD

**Issue by dkezri** [domoritz/leaflet-locatecontrol#190]
Hi,

The locatecontrol working fine on firefox and IE, but i get error when testing it on chrome browser??? even when testing your demo example.
The folowing error i got on chrome:

Geolocation error: Network location provider at 'https://www.googleapis.com/' : Returned error code 400..

any help???

**Comment by domoritz** [comment]
Hmm, this may not be an error with the plug-in. Can you try the demo at https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation?

**Comment by creative-cranels** [comment]
Hi! I am getting the same error, but with error code 403:
> Geolocation error: Network location provider at 'https://www.googleapis.com/' : Returned error code 403

Using with React, leaflet v1.1.0
Can you please help?

**Comment by domoritz** [comment]
@kayoshi Does https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation work for you?

**Comment by creative-cranels** [comment]
@domoritz it says "Unable to retrieve your location" in demo =( Maybe I am doing something wrong?

**Comment by domoritz** [comment]
If https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation doesn't work, then it's an issue with your browser and not this plugin. I'd start debugging there.

**Comment by creative-cranels** [comment]
ok, I'll keep searching for answers =)

**Comment by Jarzka** [comment]
This happened to me too. I had to enable location services on my Mac.

**Comment by rfearing** [comment]
@Jarzka so many rabbit trails until I saw this. Thank you.

**Comment by vinayvinu9876** [comment]
Hii , even i have similar issue "Network location provider at 'https://www.googleapis.com/' : No response received."

**Comment by rajatgalav** [comment]
Hi , i am also facing same issue "Network location provider at 'https://www.googleapis.com/' : No response received.". Even after enabling location permission, it is showing same error.

**Comment by eldano1995** [comment]
Same Here.

**Comment by steele-cjf** [comment]
hi,what solution?

**Comment by Santosh008** [comment]
Did we ever find a solution to this? I am also facing same issue with 
code: 2
message: "Network location provider at 'https://www.googleapis.com/' : No response received."

**Comment by yiiman-dev** [comment]
google limited some countries from use location api in chrome
so if you are using VPN everyThink is ok but when disable VPN, you can not use location API
i am searching for solve this problem too

**Comment by alisafa1371** [comment]
Hi I have the same problem but I did not work even with using VPN. and also I cant get location even on developer mozila

**Comment by Msgau** [comment]
It seems that this problem is exclusive to chromium, maybe chrome too. I tried the same code on firefox, edge and opera and it works fine without error

I maybe found an answer here => https://developer.chrome.com/blog/geolocation-on-secure-contexts-only

"Chrome has [public intent](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins) to deprecate powerful features like geolocation on non-secure origins, and we hope that others will follow.

Starting with Chrome 50, Chrome no longer supports [obtaining the user's location](https://developers.google.com/web/fundamentals/native-hardware/user-location/) using [the HTML5 Geolocation API](https://developer.mozilla.org/docs/Web/API/Geolocation/Using_geolocation) from pages delivered by non-secure connections. This means that the page that's making the Geolocation API call must be served from a [secure context](https://w3c.github.io/webappsec-secure-contexts/) such as [HTTPS](https://developer.chrome.com/web/fundamentals/security/encrypt-in-transit/enable-https)."
