### ISSUE TITLE
Hardcoded setView option in _locateOptions

### ISSUE THREAD

**Issue by johngian** [domoritz/leaflet-locatecontrol#38]
Hi everyone,

I would like to use leaflet-locatecontrol but I encounter an issue with the `locate()` functionality.

As far as I can understand here [1] you force `setView` option to be `false` in order to override it with a different value. The thing is that by forcing `setView` to be `false` in _locateOptions you render it unusable to enable the `maxZoom` `locate()` option.

What I would like to do is, on `locate`, zoom up to a point and setView. Is that possible somehow?

Thank you

[1] https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.js#L70

**Comment by domoritz** [comment]
Well, there is a `setView` option which I had to implement because of some problems with the `setView` option of `locate`. I honestly don't remember the reason. You might be able to remove the necessity if you play with it. I currently don't have the time to look into this but will happily review a pull request!!

**Comment by domoritz** [comment]
Oh, I remember. Part of the reason was that I wanted to set the view only if the location was outside the current view.

**Comment by domoritz** [comment]
Closing this now. Please reopen if you feel this is still an issue.
