### ISSUE TITLE
Question: maxZoom

### ISSUE THREAD

**Issue by Diolor** [domoritz/leaflet-locatecontrol#40]
It's kind of simple but I have stuck. How can I set the map zoom upon location discovery?

With simply `.locate()` I used:

```
.locate({
       setView: true, 
       maxZoom: 10
});
```

But now I try and this doesn't work.

```
map.addControl(L.control.locate({
       setView: true, 
       maxZoom: 10
}));
```

Thanks

**Comment by domoritz** [comment]
Thank you. I am aware of this issue but haven't had the time to fix it. Generally, you need to pass options for `locate` as `locateOptions`. 

So, you would need to write

``` js
map.addControl(L.control.locate({
       setView: true, 
       locateOptions: {
               maxZoom: 10
}}));
```

However, the way moving the map is implemented, `maxZoom` is not implemented. The problem is that I had to implement the whole code that sets the view myself because I wanted to be able to not set the view in some cases (we can already see the marker...). You would need to add this and I'd be happy to review the pull request.

**Comment by thecristen** [comment]
Is there any workaround to this? I'd really like to be able to make a map with geolocation that doesn't automatically zoom ALL the way in.

**Comment by domoritz** [comment]
Someone would need to look into the leaflet implementation and see whether there is a way to use a maxZoom setting. At the moment, I am using http://leafletjs.com/reference.html#rectangle-setbounds to zoom/pan and it does not take a maxZoom option. 

One thing you can do is increasing the padding but that is certainly not the best way to do it. You could hack the code to use a padding that is higher if you are zoomed in further. But that is very hacky. Better, as said earlier, would be to look into the code and see whether there is a clean way to set the bounds with a maxZoom option but I don't have the time for this right now, sorry.

**Comment by thecristen** [comment]
Actually I incorporated the changes in the code linked above my comment and it works fine for me.

**Comment by domoritz** [comment]
No, it doesn't. It always uses the maximum zoom level even if it is too high. The variable should be called `zoomLevel`.
